spring.application.name=cep-backend

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://LAPTOP-CCRK0TGK:1433;databaseName=CEP;encrypt=true;trustServerCertificate=true
spring.datasource.username=aq
spring.datasource.password=5187153daq

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.sql.init.mode=never

spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:1772285208@qq.com}
spring.mail.password=${MAIL_PASSWORD:cajshfutenvfbehf}
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.auth.code.expire-minutes=10
app.auth.code.resend-seconds=60
app.auth.token.access-expire-minutes=15
app.auth.token.refresh-expire-days=7
app.auth.mail.subject=校园易物注册验证码
app.auth.mail.from=${MAIL_FROM:1772285208@qq.com}
