spring.application.name=cep-backend

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://LAPTOP-CCRK0TGK:1433;databaseName=CEP;encrypt=true;trustServerCertificate=true
spring.datasource.username=aq
spring.datasource.password=5187153daq

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
